# -*- coding: utf-8 -*-

from src.research_lab.event_sweeps import (
    build_event_sweeps,
    event_to_sweep,
    sweep_proposal_dict,
)
from src.research_lab.event_cluster import detect_move_events
from src.research_lab.resource_policy import load_resource_policy
from src.research_lab.sweep_compile import compile_sweep
from src.research_lab.sweep_spec import validate_sweep_spec
from src.research_lab.timeframes import load_timeframe_profiles
from src.research_lab.universe import Universe

GLOB = "data/{symbol}_*.json"


def _candles(prices):
    return [
        {"ts": 1_700_000_000_000 + i * 900_000, "open": p, "high": p * 1.001,
         "low": p * 0.999, "close": p, "vol": 1000.0}
        for i, p in enumerate(prices)
    ]


def _universe():
    return Universe(
        groups={"alts": ("SOL_USDT_SWAP", "WLD_USDT_SWAP"), "core": ("BTC_USDT_SWAP",)},
        relations={"market_beta": {"SOL_USDT_SWAP": ("BTC_USDT_SWAP",)}},
    )


def test_build_event_sweeps_detects_and_attaches_related():
    prices = [100.0] * 6 + [110.0, 125.0, 140.0] + [140.0] * 6
    pairs = build_event_sweeps(
        _candles(prices), anchor_symbol="SOL_USDT_SWAP", timeframe="15m",
        universe=_universe(), window=3, min_move_pct=8.0,
    )
    assert pairs
    event, sweep = pairs[0]
    assert event.anchor_symbol == "SOL_USDT_SWAP"
    assert "BTC_USDT_SWAP" in sweep.related_symbols  # relation hint
    assert sweep.setup_family == "momentum_breakout"
    assert sweep.timeframe == "15m"


def test_event_sweep_is_valid_and_bounded():
    prices = [100.0] * 6 + [110.0, 125.0, 140.0] + [140.0] * 6
    event = detect_move_events(
        _candles(prices), anchor_symbol="SOL_USDT_SWAP", timeframe="15m",
        window=3, min_move_pct=8.0,
    )[0]
    sweep = event_to_sweep(event, setup_family="momentum_breakout")
    profiles, policy = load_timeframe_profiles(), load_resource_policy()
    result = validate_sweep_spec(sweep, timeframe_profiles=profiles, resource_policy=policy)
    assert result.ok
    exp = compile_sweep(sweep, data_glob=GLOB, timeframe_profiles=profiles, resource_policy=policy)
    assert exp.families == ["momentum_breakout"]
    assert len(exp.parameter_grid["momentum_breakout"]) <= profiles.get("15m").max_variants_per_setup


def test_1m_produces_no_full_brute_force():
    prices = [100.0] * 6 + [110.0, 125.0, 140.0] + [140.0] * 6
    pairs = build_event_sweeps(
        _candles(prices), anchor_symbol="SOL_USDT_SWAP", timeframe="1m",
        universe=_universe(), window=3, min_move_pct=8.0,
    )
    assert pairs == []  # no 1m-compatible family -> nothing generated by default


def test_no_event_no_sweep():
    flat = [100.0 + (i % 2) * 0.2 for i in range(20)]
    pairs = build_event_sweeps(
        _candles(flat), anchor_symbol="SOL_USDT_SWAP", timeframe="15m",
        universe=_universe(), window=3, min_move_pct=8.0,
    )
    assert pairs == []


def test_proposal_dict_is_public_safe():
    prices = [100.0] * 6 + [110.0, 125.0, 140.0] + [140.0] * 6
    event, sweep = build_event_sweeps(
        _candles(prices), anchor_symbol="SOL_USDT_SWAP", timeframe="15m",
        universe=_universe(), window=3, min_move_pct=8.0,
    )[0]
    d = sweep_proposal_dict(event, sweep)
    assert d["direction"] in {"up", "down"}
    assert "not a profitability claim" in d["note"]
    assert "no-lookahead" in d["note"] or "no-lookahead" in d["research_question"] or "lookahead" not in d["note"]
