@echo off
setlocal
chcp 65001 >nul 2>&1
cd /d "%~dp0\.."
set "PYTHONUTF8=1"

rem Time-bounded research loop, APPLY for 30 minutes. Each iteration queues only
rem data-ready validated proposals (capped) and runs ONE worker job, respecting the
rem resource-policy throttle (a deferred worker just waits for the next iteration -
rem no storm). NO network fetch and NO paid LLM here: data prep and LLM proposing are
rem opt-in and deliberately left OFF in this .bat.
rem
rem To let the cheap LLM PROPOSE candidates (costs money), do NOT edit this file -
rem run it explicitly with the env + flags, e.g.:
rem   set STRATEGY_LAB_LLM_ENABLED=1 & set STRATEGY_LAB_LLM_PROVIDER=alibaba
rem   set STRATEGY_LAB_LLM_BASE_URL=... & set STRATEGY_LAB_LLM_API_KEY=... & set STRATEGY_LAB_LLM_MODEL_CHEAP=...
rem   set STRATEGY_LAB_LLM_DAILY_CAP=5
rem   python -m scripts.strategy_lab.research_loop --apply --llm-propose --provider okx-public --duration-minutes 30
python -X utf8 -m scripts.strategy_lab.research_loop --apply --duration-minutes 30 --sleep-seconds 60 --max-worker-jobs-per-iteration 1 --max-queued 5
echo.
echo APPLY loop finished (queued data-ready jobs + capped worker; no network, no paid LLM).
echo Heartbeat + report: state/research_loop/ under the private research root.
set "RC=%ERRORLEVEL%"
if not "%STRATEGY_LAB_NO_PAUSE%"=="1" pause
endlocal
exit /b %RC%
